services:
  postgresql:
    container_name: readifyX_pg_sql
    image: postgres:latest
    environment:
      POSTGRES_USER: readify
      POSTGRES_PASSWORD: readify
      PGDATA: /var/lib/postgresql/data
    volumes:
      - v_postgres:/var/lib/postgresql/data
    networks:
      - readify-microservices-net
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: readifyX_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    
    volumes:
      - v_pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - readify-microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: readifyX_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - v_mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=readify
      - MONGO_INITDB_ROOT_PASSWORD=readify
    
    networks:
      - readify-microservices-net

  mongo-express:
    image: mongo-express
    container_name: readifyX_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=readify
      - ME_CONFIG_MONGODB_ADMINPASSWORD=readify
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=readify
      - ME_CONFIG_BASICAUTH_PASSWORD=readify
      - ME_CONFIG_MONGODB_URL=mongodb://readify:readify@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - readify-microservices-net

networks:
  readify-microservices-net:
    driver: bridge

volumes:
  v_postgres:
  v_pgadmin:
  v_mongo: