server:
  port: 8030

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book
    username: readify
    password: readify
  
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    file-url: http://localhost:8040/api/v1/file