server:
  port: 8010

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jbdc:postgresql://localhost:5432/user
    username: readify
    password: readify
  
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect